### PR TITLE
add support for zfill(3) of issue numbers.

### PR DESCRIPTION
**Pull request by ajurna**
This adds support for padded issue numbers from #26

### CODE REVIEW

**Comment by Casvt** [comment]
Though it's a nice start, I think it's better if we make it variable how much it fills, via a setting, and then link it to the value of issue_number instead of a new variable.

Reason being that if we add zfill 3, we're going to have people that want zfill 2 or 4 or something else. So maybe it's smart to avoid those requests and just immediately implement it "fully".

It would need a setting under File Naming called something like "Issue number padding" allowing a value of n >= 0. Then the naming variable gets padded with that amount of zero's.

I can do this myself but if you want to, you're always welcome to go for it and make a pr. I'm not going to merge this pr as I think it's not "complete" enough (as explained above).

**Comment by ajurna** [comment]
I've updated it to work like #31 . do you want me to extend it for 4? I don't know how many Comics/Manga go above 1000 issues other than one piece. maybe there is space for an option in the future for a per comic numbering system.

**Comment by Casvt** [comment]
This looks a lot better! Two little things and then I think we're good to go:

1. In the web-ui, the value of the setting is a _string_. Then we check if the submitted value is one of a set of _strings_. Then we save it in the config as a _string_. But then when we use the value, we convert it to an _int_.
Why not convert the value of the select to an _int_ in the web-ui, submit an _int_, save in the config as an _int_, and use as an _int_ (without the need to convert to it). Then the checking of a valid value in the settings can also just be `1 <= value <= 3`. Seems overly complicated to constantly switch between int and string.
2. Maybe add a little description under the setting in the UI, like other settings have. Something like "Add zero's to the front of the issue number to make it a minimum length".

**Comment by ajurna** [comment]
I was concerned that since the the field in the database is a varchar it may be interpreted and returned as a string whatever you do. having the conversion on the only area where it matters makes sure that when it transitions from javascript -> python -> sqlite  that it will indeed be a number.

**Comment by Casvt** [comment]
The field in the database is a blob. That means that if you insert an int, you'll just get an int back when you fetch it.

```sql
		CREATE TABLE IF NOT EXISTS config(
			key VARCHAR(100) PRIMARY KEY,
			value BLOB
		);
```
[Source](https://github.com/Casvt/Kapowarr/blob/development/backend/db.py#L258)

Proof:
```python3
cursor.execute("CREATE TABLE test(value BLOB);")
cursor.execute("INSERT INTO test(value) VALUES (?), (?)", (1, '1'))
cursor.execute("SELECT * FROM test").fetchall()
[(1,), ('1',)]
```

**Comment by ajurna** [comment]
ok, where would you want to do that cast then? I assume in settings? a select field only holds strings afaik.

**Comment by Casvt** [comment]
Right at the beginning, in the web-ui using js. The API request should already contain ints. Something like the following should suffice:
```javascript
parseInt(document.querySelector('#issue-padding').value) // converts value of select from a string to an integer
```

**Comment by Casvt** [comment]
Looks good. I'll merge and include it in the next release. Thank you for contributing.

**Pull request merged**
