### PR TITLE
Update installation.md - add ubuntu install instructions

### PR DESCRIPTION
**Pull request by RationalAnarchist**
Installation instructions for Ubuntu.  I can't be sure that the markdown is correct - can't find a way to preview it, but hopefully it's ok.  Aiming to spin up some other distros at the weekend to confirm if the same sort of thing will work for them.

### CODE REVIEW

**Comment by RationalAnarchist** [comment]
Links to [https://github.com/Casvt/Kapowarr/issues/57](https://github.com/Casvt/Kapowarr/issues/57)

**Comment by Berserkir-Wolf** [comment]
Any particular reason your user is defined as 'pi' on a Ubuntu guide? I know that user definitely doesn't exist on at least a dozen of the ubuntu servers I administer.

**Comment by ajurna** [comment]
a new service user called kapowarr should be added. usually it's best practice to run as service as a service account and isolate it's permissions.

**Comment by RationalAnarchist** [comment]
You're both right - sorry!  That was my default user - will update when I get the chance (may not be until the weekend)

**Comment by Casvt** [comment]
How's it going?

**Comment by Casvt** [comment]
I'm going to close the PR, seeing that it does not appear to be worked on anymore. But the work that you've done up to now will for sure be used, so thank you for that.

**Pull request closed without merging**
